### ISSUE TITLE
test data

### ISSUE THREAD

**Issue by alexlib** [JiriVejrazka/1pxPIV_matlab#1]
Hi
Can you please, add test data to the repository, so the tests are performed on the same set? 

thanks
Alex

**Comment by JiriVejrazka** [comment]
Hi, tomorrow I will send you another message, with suitable data. In fact, the intended data set was too large...

Jiri

Odesláno z mého Windows Phone
________________________________
Od:Alex Liberzon
Odesláno:3.7.2015 22:11
Komu:JiriVejrazka/1pxPIV_matlab
Předmět:[1pxPIV_matlab] test data (#1)


Hi
Can you please, add test data to the repository, so the tests are performed on the same set?

thanks
Alex

-
